/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Automated Course Scheduler API
 * API for the Automated Course Scheduler system
 * OpenAPI spec version: 1.0.0
 */
import { axiosInstance } from './axiosInstance';
export interface BodyUploadCoursesUploadCoursesPost {
  file: string;
}

export interface BodyUploadFacultyPreferencesUploadFacultyPreferencesPost {
  file: string;
}

export interface BodyUploadTimePreferencesUploadTimePreferencesPost {
  file: string;
}

export interface CampusCreate {
  name: string;
  active?: boolean;
}

export interface CampusResponse {
  campus_id: number;
  name: string;
  active: boolean;
}

export type CampusUpdateName = string | null;

export type CampusUpdateActive = boolean | null;

export interface CampusUpdate {
  name?: CampusUpdateName;
  active?: CampusUpdateActive;
}

export type CommentResponseParentId = number | null;

export interface CommentResponse {
  comment_id: number;
  user_id: number;
  section_id: number;
  parent_id: CommentResponseParentId;
  content: string;
  resolved: boolean;
  active: boolean;
  created_at: string;
  user: CommentUserInfo;
}

export interface CommentSchema {
  section_id: number;
  user_id: number;
  content: string;
}

export interface CommentUserInfo {
  user_id: number;
  first_name: string;
  last_name: string;
  email: string;
}

export interface CourseCreate {
  /** @minLength 1 */
  name: string;
  /** @minLength 1 */
  description: string;
  /** @minimum 0 */
  credits: number;
  priority?: boolean;
}

export interface CourseInfo {
  course_id: number;
  name: string;
  description: string;
  credits: number;
}

export interface CoursePreferenceInfo {
  course_id: number;
  course_name: string;
  preference: string;
}

export type CourseResponseCourseDescription = string | null;

export type CourseResponseCourseNo = number | null;

export type CourseResponseCourseSubject = string | null;

export type CourseResponseCourseName = string | null;

export type CourseResponseSectionCount = number | null;

export interface CourseResponse {
  CourseID: number;
  CourseDescription?: CourseResponseCourseDescription;
  CourseNo?: CourseResponseCourseNo;
  CourseSubject?: CourseResponseCourseSubject;
  CourseName?: CourseResponseCourseName;
  SectionCount?: CourseResponseSectionCount;
  Priority?: boolean;
  QualifiedFaculty?: number;
}

export type CourseUpdateName = string | null;

export type CourseUpdateDescription = string | null;

export type CourseUpdateCredits = number | null;

export type CourseUpdatePriority = boolean | null;

export interface CourseUpdate {
  name?: CourseUpdateName;
  description?: CourseUpdateDescription;
  credits?: CourseUpdateCredits;
  priority?: CourseUpdatePriority;
}

export type FacultyCreatePhoneNumber = string | null;

export type FacultyCreateTitle = string | null;

export interface FacultyCreate {
  /** */
  nuid: number;
  /** @minLength 1 */
  first_name: string;
  /** @minLength 1 */
  last_name: string;
  /** @minLength 1 */
  email: string;
  /** */
  campus: number;
  phone_number?: FacultyCreatePhoneNumber;
  title?: FacultyCreateTitle;
  active?: boolean;
  /** @minimum 1 */
  max_load?: number;
}

export type FacultyProfileResponseTitle = string | null;

export type FacultyProfileResponseMaxLoad = number | null;

export interface FacultyProfileResponse {
  nuid: number;
  first_name: string;
  last_name: string;
  email: string;
  title?: FacultyProfileResponseTitle;
  campus: number;
  active: boolean;
  maxLoad?: FacultyProfileResponseMaxLoad;
  needsAdminReview?: boolean;
  course_preferences: CoursePreferenceInfo[];
  meeting_preferences: MeetingPreferenceInfo[];
}

export type FacultyResponseFirstName = string | null;

export type FacultyResponseLastName = string | null;

export type FacultyResponseEmail = string | null;

export type FacultyResponseTitle = string | null;

export type FacultyResponseCampus = number | null;

export type FacultyResponseActive = boolean | null;

export type FacultyResponseMaxLoad = number | null;

export interface FacultyResponse {
  nuid: number;
  first_name?: FacultyResponseFirstName;
  last_name?: FacultyResponseLastName;
  email?: FacultyResponseEmail;
  title?: FacultyResponseTitle;
  campus?: FacultyResponseCampus;
  active?: FacultyResponseActive;
  maxLoad?: FacultyResponseMaxLoad;
}

export type FacultyUpdateFirstName = string | null;

export type FacultyUpdateLastName = string | null;

export type FacultyUpdateEmail = string | null;

export type FacultyUpdateCampus = number | null;

export type FacultyUpdatePhoneNumber = string | null;

export type FacultyUpdateTitle = string | null;

export type FacultyUpdateActive = boolean | null;

export type FacultyUpdateMaxLoad = number | null;

export interface FacultyUpdate {
  first_name?: FacultyUpdateFirstName;
  last_name?: FacultyUpdateLastName;
  email?: FacultyUpdateEmail;
  campus?: FacultyUpdateCampus;
  phone_number?: FacultyUpdatePhoneNumber;
  title?: FacultyUpdateTitle;
  active?: FacultyUpdateActive;
  max_load?: FacultyUpdateMaxLoad;
}

export interface HTTPValidationError {
  detail?: ValidationError[];
}

export interface InstructorInfo {
  nuid: number;
  first_name: string;
  last_name: string;
  title: string;
  email: string;
  course_preferences: CoursePreferenceInfo[];
  meeting_preferences: MeetingPreferenceInfo[];
}

export interface InviteLinkResponse {
  first_name: string;
  last_name: string;
  email: string;
  invite_link: string;
}

export interface InviteRequest {
  /** */
  nuid: number;
  role?: string;
}

export interface InviteResponse {
  user: UserResponse;
  signup_url: string;
}

export interface MeetingPreferenceInfo {
  time_block_id: number;
  preference: string;
}

/**
 * Returned for each active lock when polling a schedule's lock state.
 */
export interface ScheduleActiveLockResponse {
  section_id: number;
  locked_by: number;
  display_name: string;
  expires_at: string;
}

export interface ScheduleCreate {
  name: string;
  semester_id: number;
  campus: number;
  new_courses?: number[];
}

export interface ScheduleResponse {
  schedule_id: number;
  name: string;
  semester_id: number;
  draft: boolean;
  campus: number;
  active: boolean;
  course_list?: CourseResponse[];
}

export type ScheduleUpdateName = string | null;

export type ScheduleUpdateActive = boolean | null;

export interface ScheduleUpdate {
  name?: ScheduleUpdateName;
  active?: ScheduleUpdateActive;
}

export type SectionCreateFacultyNuids = number[] | null;

export interface SectionCreate {
  schedule_id: number;
  time_block_id: number;
  course_id: number;
  capacity: number;
  section_number: number;
  faculty_nuids?: SectionCreateFacultyNuids;
}

/**
 * Returned on successful lock acquisition or refresh.
 */
export interface SectionLockResponse {
  section_lock_id: number;
  section_id: number;
  locked_by: number;
  locked_at: string;
  expires_at: string;
}

export type SectionResponseRoom = string | null;

export type SectionResponseAssignmentScore = number | null;

export interface SectionResponse {
  section_id: number;
  schedule_id: number;
  time_block_id: number;
  course_id: number;
  capacity: number;
  section_number: number;
  room?: SectionResponseRoom;
  assignment_score?: SectionResponseAssignmentScore;
}

export type SectionRichResponseRoom = string | null;

export interface SectionRichResponse {
  section_id: number;
  section_number: number;
  capacity: number;
  room?: SectionRichResponseRoom;
  schedule_id: number;
  course: CourseInfo;
  time_block: TimeBlockInfo;
  instructors: InstructorInfo[];
}

export type SectionUpdateTimeBlockId = number | null;

export type SectionUpdateCourseId = number | null;

export type SectionUpdateCapacity = number | null;

export type SectionUpdateRoom = string | null;

export type SectionUpdateCrosslistedSectionId = number | null;

export type SectionUpdateFacultyNuids = number[] | null;

export interface SectionUpdate {
  time_block_id?: SectionUpdateTimeBlockId;
  course_id?: SectionUpdateCourseId;
  capacity?: SectionUpdateCapacity;
  room?: SectionUpdateRoom;
  crosslisted_section_id?: SectionUpdateCrosslistedSectionId;
  faculty_nuids?: SectionUpdateFacultyNuids;
}

export interface SemesterCreate {
  season: string;
  year: number;
  active?: boolean;
}

export interface SemesterResponse {
  semester_id: number;
  season: string;
  year: number;
  active: boolean;
}

export type SemesterUpdateSeason = string | null;

export type SemesterUpdateYear = number | null;

export type SemesterUpdateActive = boolean | null;

export interface SemesterUpdate {
  season?: SemesterUpdateSeason;
  year?: SemesterUpdateYear;
  active?: SemesterUpdateActive;
}

export interface TimeBlockInfo {
  time_block_id: number;
  days: string;
  start_time: string;
  end_time: string;
}

export type TimeBlockResponseBlockID = number | null;

export type TimeBlockResponseCampusID = number | null;

export type TimeBlockResponseCount = number | null;

/**
 * CampusTimeBlock.
 */
export interface TimeBlockResponse {
  BlockID?: TimeBlockResponseBlockID;
  CampusID?: TimeBlockResponseCampusID;
  Count?: TimeBlockResponseCount;
}

export type UploadResponseErrors = string[] | null;

export interface UploadResponse {
  status: string;
  message: string;
  records_processed?: number;
  records_successful?: number;
  records_failed?: number;
  available_faculty?: number[];
  errors?: UploadResponseErrors;
}

export interface UserResponse {
  user_id: number;
  nuid: number;
  first_name: string;
  last_name: string;
  email: string;
  role: string;
  active: boolean;
}

export type ValidationErrorLocItem = string | number;

export type ValidationErrorCtx = { [key: string]: unknown };

export interface ValidationError {
  loc: ValidationErrorLocItem[];
  msg: string;
  type: string;
  input?: unknown;
  ctx?: ValidationErrorCtx;
}

export type GetSchedulesSchedulesGetParams = {
campus_id?: number | null;
semester_id?: number | null;
};

export type GetCoursesCoursesGetParams = {
/**
 * Filter to courses with sections in this schedule
 */
schedule_id?: number | null;
};

export type GetCourseCoursesCourseIdGetParams = {
/**
 * Section count for this schedule only
 */
schedule_id?: number | null;
};

export type GetFacultyFacultyGetParams = {
/**
 * Filter by campus name
 */
campus?: string | null;
/**
 * Filter to only active faculty
 */
active_only?: boolean;
};

export type GetTimeBlocksTimeBlocksGetParams = {
/**
 * Filter by campus ID
 */
campus_id?: number | null;
};

export type GetAllCampusesCampusesGetParams = {
name?: string | null;
};

export const getAutomatedCourseSchedulerAPI = () => {
/**
 * Create a new section in a schedule.
 * @summary Create Section
 */
const createSectionSectionsPost = (
    sectionCreate: SectionCreate,
 ) => {
      return axiosInstance<SectionResponse>(
      {url: `/sections`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: sectionCreate
    },
      );
    }
  
/**
 * Acquire (or refresh) the lock on this section, then apply the update.

Fails with 423 if another user currently holds the lock.
Broadcasts section_updated to connected clients on success.
 * @summary Update Section
 */
const updateSectionSectionsSectionIdPatch = (
    sectionId: number,
    sectionUpdate: SectionUpdate,
 ) => {
      return axiosInstance<SectionResponse>(
      {url: `/sections/${sectionId}`, method: 'PATCH',
      headers: {'Content-Type': 'application/json', },
      data: sectionUpdate
    },
      );
    }
  
/**
 * Delete a section from a schedule.
 * @summary Delete Section
 */
const deleteSectionSectionsSectionIdDelete = (
    sectionId: number,
 ) => {
      return axiosInstance<void>(
      {url: `/sections/${sectionId}`, method: 'DELETE'
    },
      );
    }
  
/**
 * @summary Get Schedules
 */
const getSchedulesSchedulesGet = (
    params?: GetSchedulesSchedulesGetParams,
 ) => {
      return axiosInstance<ScheduleResponse[]>(
      {url: `/schedules`, method: 'GET',
        params
    },
      );
    }
  
/**
 * Create a new schedule draft.
 * @summary Create Schedule
 */
const createScheduleSchedulesPost = (
    scheduleCreate: ScheduleCreate,
 ) => {
      return axiosInstance<ScheduleResponse>(
      {url: `/schedules`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: scheduleCreate
    },
      );
    }
  
/**
 * Retrieve a specific schedule.
 * @summary Get Schedule
 */
const getScheduleSchedulesScheduleIdGet = (
    scheduleId: number,
 ) => {
      return axiosInstance<ScheduleResponse>(
      {url: `/schedules/${scheduleId}`, method: 'GET'
    },
      );
    }
  
/**
 * Update schedule metadata (name, complete status, etc.).
 * @summary Update Schedule
 */
const updateScheduleSchedulesScheduleIdPut = (
    scheduleId: number,
    scheduleUpdate: ScheduleUpdate,
 ) => {
      return axiosInstance<ScheduleResponse>(
      {url: `/schedules/${scheduleId}`, method: 'PUT',
      headers: {'Content-Type': 'application/json', },
      data: scheduleUpdate
    },
      );
    }
  
/**
 * Delete a schedule and all its sections.
 * @summary Delete Schedule
 */
const deleteScheduleSchedulesScheduleIdDelete = (
    scheduleId: number,
 ) => {
      return axiosInstance<void>(
      {url: `/schedules/${scheduleId}`, method: 'DELETE'
    },
      );
    }
  
/**
 * Get all sections for a specific schedule.
 * @summary Get Schedule Sections
 */
const getScheduleSectionsSchedulesScheduleIdSectionsGet = (
    scheduleId: number,
 ) => {
      return axiosInstance<SectionResponse[]>(
      {url: `/schedules/${scheduleId}/sections`, method: 'GET'
    },
      );
    }
  
/**
 * Get all sections with denormalized course, time block, and instructor data.
 * @summary Get Schedule Sections Rich
 */
const getScheduleSectionsRichSchedulesScheduleIdSectionsRichGet = (
    scheduleId: number,
 ) => {
      return axiosInstance<SectionRichResponse[]>(
      {url: `/schedules/${scheduleId}/sections/rich`, method: 'GET'
    },
      );
    }
  
/**
 * Export a finalized schedule in CourseLeaf-compatible CSV format.
 * @summary Export Schedule Csv
 */
const exportScheduleCsvSchedulesScheduleIdExportCsvGet = (
    scheduleId: number,
 ) => {
      return axiosInstance<unknown>(
      {url: `/schedules/${scheduleId}/export/csv`, method: 'GET'
    },
      );
    }
  
/**
 * Get all active locks for a schedule.

Args:
    schedule_id: ID of the schedule to query locks for.
    db: Database session.

Returns:
    List of active locks with user display name included.
 * @summary Get Schedule Locks
 */
const getScheduleLocksSchedulesScheduleIdLocksGet = (
    scheduleId: number,
 ) => {
      return axiosInstance<ScheduleActiveLockResponse[]>(
      {url: `/schedules/${scheduleId}/locks`, method: 'GET'
    },
      );
    }
  
/**
 * Get all semesters, with optional filtering by campus, semester name, or year.
 * @summary Get All Semesters
 */
const getAllSemestersSemestersGet = (
    
 ) => {
      return axiosInstance<SemesterResponse[]>(
      {url: `/semesters`, method: 'GET'
    },
      );
    }
  
/**
 * Create a new semester.
 * @summary Create Semester
 */
const createSemesterSemestersPost = (
    semesterCreate: SemesterCreate,
 ) => {
      return axiosInstance<SemesterCreate>(
      {url: `/semesters`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: semesterCreate
    },
      );
    }
  
/**
 * Retrieve a specific semester.
 * @summary Get Semester
 */
const getSemesterSemestersSemesterIdGet = (
    semesterId: number,
 ) => {
      return axiosInstance<SemesterResponse>(
      {url: `/semesters/${semesterId}`, method: 'GET'
    },
      );
    }
  
/**
 * Update semester metadata (name, complete status, etc.).
 * @summary Update Semester
 */
const updateSemesterSemestersSemesterIdPut = (
    semesterId: number,
    semesterUpdate: SemesterUpdate,
 ) => {
      return axiosInstance<SemesterResponse>(
      {url: `/semesters/${semesterId}`, method: 'PUT',
      headers: {'Content-Type': 'application/json', },
      data: semesterUpdate
    },
      );
    }
  
/**
 * Delete a semester and all its sections.
 * @summary Delete Semester
 */
const deleteSemesterSemestersSemesterIdDelete = (
    semesterId: number,
 ) => {
      return axiosInstance<void>(
      {url: `/semesters/${semesterId}`, method: 'DELETE'
    },
      );
    }
  
/**
 * Retrieve all courses, optionally filtered by schedule
 * @summary Get Courses
 */
const getCoursesCoursesGet = (
    params?: GetCoursesCoursesGetParams,
 ) => {
      return axiosInstance<CourseResponse[]>(
      {url: `/courses`, method: 'GET',
        params
    },
      );
    }
  
/**
 * Create a new course.
 * @summary Create Course
 */
const createCourseCoursesPost = (
    courseCreate: CourseCreate,
 ) => {
      return axiosInstance<CourseResponse>(
      {url: `/courses`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: courseCreate
    },
      );
    }
  
/**
 * Retrieve a course by ID with section count.
 * @summary Get Course
 */
const getCourseCoursesCourseIdGet = (
    courseId: number,
    params?: GetCourseCoursesCourseIdGetParams,
 ) => {
      return axiosInstance<CourseResponse>(
      {url: `/courses/${courseId}`, method: 'GET',
        params
    },
      );
    }
  
/**
 * Partially update a course.
 * @summary Update Course
 */
const updateCourseCoursesCourseIdPatch = (
    courseId: number,
    courseUpdate: CourseUpdate,
 ) => {
      return axiosInstance<CourseResponse>(
      {url: `/courses/${courseId}`, method: 'PATCH',
      headers: {'Content-Type': 'application/json', },
      data: courseUpdate
    },
      );
    }
  
/**
 * Delete a course with no sections.
 * @summary Delete Course
 */
const deleteCourseCoursesCourseIdDelete = (
    courseId: number,
 ) => {
      return axiosInstance<void>(
      {url: `/courses/${courseId}`, method: 'DELETE'
    },
      );
    }
  
/**
 * Retrieve all faculty members.
 * @summary Get Faculty
 */
const getFacultyFacultyGet = (
    params?: GetFacultyFacultyGetParams,
 ) => {
      return axiosInstance<FacultyResponse[]>(
      {url: `/faculty`, method: 'GET',
        params
    },
      );
    }
  
/**
 * Create a new faculty member.
 * @summary Create Faculty
 */
const createFacultyFacultyPost = (
    facultyCreate: FacultyCreate,
 ) => {
      return axiosInstance<FacultyResponse>(
      {url: `/faculty`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: facultyCreate
    },
      );
    }
  
/**
 * Retrieve faculty profile with course and time preferences.
 * @summary Get Faculty Profile
 */
const getFacultyProfileFacultyNuidGet = (
    nuid: number,
 ) => {
      return axiosInstance<FacultyProfileResponse>(
      {url: `/faculty/${nuid}`, method: 'GET'
    },
      );
    }
  
/**
 * Partially update faculty demographics and status.
 * @summary Update Faculty
 */
const updateFacultyFacultyNuidPatch = (
    nuid: number,
    facultyUpdate: FacultyUpdate,
 ) => {
      return axiosInstance<FacultyResponse>(
      {url: `/faculty/${nuid}`, method: 'PATCH',
      headers: {'Content-Type': 'application/json', },
      data: facultyUpdate
    },
      );
    }
  
/**
 * Delete a faculty member and their preferences and assignments.
 * @summary Delete Faculty
 */
const deleteFacultyFacultyNuidDelete = (
    nuid: number,
 ) => {
      return axiosInstance<void>(
      {url: `/faculty/${nuid}`, method: 'DELETE'
    },
      );
    }
  
/**
 * @summary Build Profiles
 */
const buildProfilesFacultyBuildProfilesPost = (
    buildProfilesFacultyBuildProfilesPostBody: number[],
 ) => {
      return axiosInstance<FacultyProfileResponse[]>(
      {url: `/faculty/build_profiles`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: buildProfilesFacultyBuildProfilesPostBody
    },
      );
    }
  
/**
 * Retrieve all time blocks, optionally filtered by campus.
 * @summary Get Time Blocks
 */
const getTimeBlocksTimeBlocksGet = (
    params?: GetTimeBlocksTimeBlocksGetParams,
 ) => {
      return axiosInstance<TimeBlockResponse[]>(
      {url: `/time-blocks`, method: 'GET',
        params
    },
      );
    }
  
/**
 * Retrieve all campuses, optionally filtered by name.
 * @summary Get All Campuses
 */
const getAllCampusesCampusesGet = (
    params?: GetAllCampusesCampusesGetParams,
 ) => {
      return axiosInstance<CampusResponse[]>(
      {url: `/campuses`, method: 'GET',
        params
    },
      );
    }
  
/**
 * Create a new campus.
 * @summary Create Campus
 */
const createCampusCampusesPost = (
    campusCreate: CampusCreate,
 ) => {
      return axiosInstance<CampusResponse>(
      {url: `/campuses`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: campusCreate
    },
      );
    }
  
/**
 * Retrieve a specific campus by ID.
 * @summary Get Campus
 */
const getCampusCampusesCampusIdGet = (
    campusId: number,
 ) => {
      return axiosInstance<CampusResponse>(
      {url: `/campuses/${campusId}`, method: 'GET'
    },
      );
    }
  
/**
 * Update campus metadata (name, etc.).
 * @summary Update Campus
 */
const updateCampusCampusesCampusIdPut = (
    campusId: number,
    campusUpdate: CampusUpdate,
 ) => {
      return axiosInstance<CampusResponse>(
      {url: `/campuses/${campusId}`, method: 'PUT',
      headers: {'Content-Type': 'application/json', },
      data: campusUpdate
    },
      );
    }
  
/**
 * Delete a campus.
 * @summary Delete Campus
 */
const deleteCampusCampusesCampusIdDelete = (
    campusId: number,
 ) => {
      return axiosInstance<void>(
      {url: `/campuses/${campusId}`, method: 'DELETE'
    },
      );
    }
  
/**
 * Upload a CSV file containing course offering data.
 * @summary Upload Courses
 */
const uploadCoursesUploadCoursesPost = (
    bodyUploadCoursesUploadCoursesPost: BodyUploadCoursesUploadCoursesPost,
 ) => {const formData = new FormData();
formData.append(`file`, bodyUploadCoursesUploadCoursesPost.file)

      return axiosInstance<UploadResponse>(
      {url: `/upload/courses`, method: 'POST',
      headers: {'Content-Type': 'multipart/form-data', },
       data: formData
    },
      );
    }
  
/**
 * Upload a CSV file containing faculty preference data.
 * @summary Upload Faculty Preferences
 */
const uploadFacultyPreferencesUploadFacultyPreferencesPost = (
    bodyUploadFacultyPreferencesUploadFacultyPreferencesPost: BodyUploadFacultyPreferencesUploadFacultyPreferencesPost,
 ) => {const formData = new FormData();
formData.append(`file`, bodyUploadFacultyPreferencesUploadFacultyPreferencesPost.file)

      return axiosInstance<UploadResponse>(
      {url: `/upload/faculty-preferences`, method: 'POST',
      headers: {'Content-Type': 'multipart/form-data', },
       data: formData
    },
      );
    }
  
/**
 * Upload a CSV file containing faculty time preference data.
 * @summary Upload Time Preferences
 */
const uploadTimePreferencesUploadTimePreferencesPost = (
    bodyUploadTimePreferencesUploadTimePreferencesPost: BodyUploadTimePreferencesUploadTimePreferencesPost,
 ) => {const formData = new FormData();
formData.append(`file`, bodyUploadTimePreferencesUploadTimePreferencesPost.file)

      return axiosInstance<UploadResponse>(
      {url: `/upload/time-preferences`, method: 'POST',
      headers: {'Content-Type': 'multipart/form-data', },
       data: formData
    },
      );
    }
  
/**
 * @summary Post Comment
 */
const postCommentCommentsPost = (
    commentSchema: CommentSchema,
 ) => {
      return axiosInstance<CommentResponse>(
      {url: `/comments`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: commentSchema
    },
      );
    }
  
/**
 * @summary Post Reply
 */
const postReplyCommentsParentIdPost = (
    parentId: number,
    commentSchema: CommentSchema,
 ) => {
      return axiosInstance<CommentResponse>(
      {url: `/comments/${parentId}`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: commentSchema
    },
      );
    }
  
/**
 * @summary Get Comments
 */
const getCommentsCommentsSectionIdGet = (
    sectionId: number,
 ) => {
      return axiosInstance<CommentResponse[]>(
      {url: `/comments/${sectionId}`, method: 'GET'
    },
      );
    }
  
/**
 * @summary Delete Comment
 */
const deleteCommentCommentsCommentIdDelete = (
    commentId: number,
 ) => {
      return axiosInstance<CommentResponse[]>(
      {url: `/comments/${commentId}`, method: 'DELETE'
    },
      );
    }
  
/**
 * @summary Resolve Comment
 */
const resolveCommentCommentsCommentIdPut = (
    commentId: number,
 ) => {
      return axiosInstance<void>(
      {url: `/comments/${commentId}`, method: 'PUT'
    },
      );
    }
  
/**
 * Acquire a lock on a section for editing.

Raises:
    HTTPException: 403 if the caller does not have the admin role.
    HTTPException: 423 if the section is locked by another user.
 * @summary Acquire Lock
 */
const acquireLockSectionsSectionIdLockPost = (
    sectionId: number,
 ) => {
      return axiosInstance<SectionLockResponse>(
      {url: `/sections/${sectionId}/lock`, method: 'POST'
    },
      );
    }
  
/**
 * Release a lock on a section.

Raises:
    HTTPException: 403 if the caller does not own an active lock.
 * @summary Release Lock
 */
const releaseLockSectionsSectionIdUnlockPost = (
    sectionId: number,
 ) => {
      return axiosInstance<unknown>(
      {url: `/sections/${sectionId}/unlock`, method: 'POST'
    },
      );
    }
  
/**
 * Invite a faculty member. Requires admin role.

Looks up the faculty record by NUID, creates a User, registers them in
Auth0, generates a password-change ticket, and sends an invite email.
 * @summary Create Invite
 */
const createInviteApiInvitesPost = (
    inviteRequest: InviteRequest,
 ) => {
      return axiosInstance<InviteResponse>(
      {url: `/api/invites`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: inviteRequest
    },
      );
    }
  
/**
 * Return invite links for all active faculty without a linked account.

Creates pending User records for any who were not yet invited.
Requires admin role.
 * @summary Export Invites
 */
const exportInvitesApiInvitesExportGet = (
    
 ) => {
      return axiosInstance<InviteLinkResponse[]>(
      {url: `/api/invites/export`, method: 'GET'
    },
      );
    }
  
/**
 * Return all users. Requires admin role.
 * @summary List Users
 */
const listUsersApiUsersGet = (
    
 ) => {
      return axiosInstance<UserResponse[]>(
      {url: `/api/users`, method: 'GET'
    },
      );
    }
  
/**
 * Return the profile of the currently authenticated user.
 * @summary Get Me
 */
const getMeApiUsersMeGet = (
    
 ) => {
      return axiosInstance<UserResponse>(
      {url: `/api/users/me`, method: 'GET'
    },
      );
    }
  
/**
 * Return a single user by ID. Requires admin role.
 * @summary Get User
 */
const getUserApiUsersUserIdGet = (
    userId: number,
 ) => {
      return axiosInstance<UserResponse>(
      {url: `/api/users/${userId}`, method: 'GET'
    },
      );
    }
  
/**
 * @summary Root
 */
const rootGet = (
    
 ) => {
      return axiosInstance<unknown>(
      {url: `/`, method: 'GET'
    },
      );
    }
  
return {createSectionSectionsPost,updateSectionSectionsSectionIdPatch,deleteSectionSectionsSectionIdDelete,getSchedulesSchedulesGet,createScheduleSchedulesPost,getScheduleSchedulesScheduleIdGet,updateScheduleSchedulesScheduleIdPut,deleteScheduleSchedulesScheduleIdDelete,getScheduleSectionsSchedulesScheduleIdSectionsGet,getScheduleSectionsRichSchedulesScheduleIdSectionsRichGet,exportScheduleCsvSchedulesScheduleIdExportCsvGet,getScheduleLocksSchedulesScheduleIdLocksGet,getAllSemestersSemestersGet,createSemesterSemestersPost,getSemesterSemestersSemesterIdGet,updateSemesterSemestersSemesterIdPut,deleteSemesterSemestersSemesterIdDelete,getCoursesCoursesGet,createCourseCoursesPost,getCourseCoursesCourseIdGet,updateCourseCoursesCourseIdPatch,deleteCourseCoursesCourseIdDelete,getFacultyFacultyGet,createFacultyFacultyPost,getFacultyProfileFacultyNuidGet,updateFacultyFacultyNuidPatch,deleteFacultyFacultyNuidDelete,buildProfilesFacultyBuildProfilesPost,getTimeBlocksTimeBlocksGet,getAllCampusesCampusesGet,createCampusCampusesPost,getCampusCampusesCampusIdGet,updateCampusCampusesCampusIdPut,deleteCampusCampusesCampusIdDelete,uploadCoursesUploadCoursesPost,uploadFacultyPreferencesUploadFacultyPreferencesPost,uploadTimePreferencesUploadTimePreferencesPost,postCommentCommentsPost,postReplyCommentsParentIdPost,getCommentsCommentsSectionIdGet,deleteCommentCommentsCommentIdDelete,resolveCommentCommentsCommentIdPut,acquireLockSectionsSectionIdLockPost,releaseLockSectionsSectionIdUnlockPost,createInviteApiInvitesPost,listUsersApiUsersGet,getMeApiUsersMeGet,getUserApiUsersUserIdGet,rootGet}};
export type CreateSectionSectionsPostResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getAutomatedCourseSchedulerAPI>['createSectionSectionsPost']>>>
export type UpdateSectionSectionsSectionIdPatchResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getAutomatedCourseSchedulerAPI>['updateSectionSectionsSectionIdPatch']>>>
export type DeleteSectionSectionsSectionIdDeleteResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getAutomatedCourseSchedulerAPI>['deleteSectionSectionsSectionIdDelete']>>>
export type GetSchedulesSchedulesGetResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getAutomatedCourseSchedulerAPI>['getSchedulesSchedulesGet']>>>
export type CreateScheduleSchedulesPostResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getAutomatedCourseSchedulerAPI>['createScheduleSchedulesPost']>>>
export type GetScheduleSchedulesScheduleIdGetResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getAutomatedCourseSchedulerAPI>['getScheduleSchedulesScheduleIdGet']>>>
export type UpdateScheduleSchedulesScheduleIdPutResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getAutomatedCourseSchedulerAPI>['updateScheduleSchedulesScheduleIdPut']>>>
export type DeleteScheduleSchedulesScheduleIdDeleteResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getAutomatedCourseSchedulerAPI>['deleteScheduleSchedulesScheduleIdDelete']>>>
export type GetScheduleSectionsSchedulesScheduleIdSectionsGetResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getAutomatedCourseSchedulerAPI>['getScheduleSectionsSchedulesScheduleIdSectionsGet']>>>
export type GetScheduleSectionsRichSchedulesScheduleIdSectionsRichGetResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getAutomatedCourseSchedulerAPI>['getScheduleSectionsRichSchedulesScheduleIdSectionsRichGet']>>>
export type ExportScheduleCsvSchedulesScheduleIdExportCsvGetResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getAutomatedCourseSchedulerAPI>['exportScheduleCsvSchedulesScheduleIdExportCsvGet']>>>
export type GetScheduleLocksSchedulesScheduleIdLocksGetResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getAutomatedCourseSchedulerAPI>['getScheduleLocksSchedulesScheduleIdLocksGet']>>>
export type GetAllSemestersSemestersGetResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getAutomatedCourseSchedulerAPI>['getAllSemestersSemestersGet']>>>
export type CreateSemesterSemestersPostResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getAutomatedCourseSchedulerAPI>['createSemesterSemestersPost']>>>
export type GetSemesterSemestersSemesterIdGetResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getAutomatedCourseSchedulerAPI>['getSemesterSemestersSemesterIdGet']>>>
export type UpdateSemesterSemestersSemesterIdPutResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getAutomatedCourseSchedulerAPI>['updateSemesterSemestersSemesterIdPut']>>>
export type DeleteSemesterSemestersSemesterIdDeleteResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getAutomatedCourseSchedulerAPI>['deleteSemesterSemestersSemesterIdDelete']>>>
export type GetCoursesCoursesGetResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getAutomatedCourseSchedulerAPI>['getCoursesCoursesGet']>>>
export type CreateCourseCoursesPostResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getAutomatedCourseSchedulerAPI>['createCourseCoursesPost']>>>
export type GetCourseCoursesCourseIdGetResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getAutomatedCourseSchedulerAPI>['getCourseCoursesCourseIdGet']>>>
export type UpdateCourseCoursesCourseIdPatchResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getAutomatedCourseSchedulerAPI>['updateCourseCoursesCourseIdPatch']>>>
export type DeleteCourseCoursesCourseIdDeleteResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getAutomatedCourseSchedulerAPI>['deleteCourseCoursesCourseIdDelete']>>>
export type GetFacultyFacultyGetResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getAutomatedCourseSchedulerAPI>['getFacultyFacultyGet']>>>
export type CreateFacultyFacultyPostResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getAutomatedCourseSchedulerAPI>['createFacultyFacultyPost']>>>
export type GetFacultyProfileFacultyNuidGetResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getAutomatedCourseSchedulerAPI>['getFacultyProfileFacultyNuidGet']>>>
export type UpdateFacultyFacultyNuidPatchResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getAutomatedCourseSchedulerAPI>['updateFacultyFacultyNuidPatch']>>>
export type DeleteFacultyFacultyNuidDeleteResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getAutomatedCourseSchedulerAPI>['deleteFacultyFacultyNuidDelete']>>>
export type BuildProfilesFacultyBuildProfilesPostResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getAutomatedCourseSchedulerAPI>['buildProfilesFacultyBuildProfilesPost']>>>
export type GetTimeBlocksTimeBlocksGetResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getAutomatedCourseSchedulerAPI>['getTimeBlocksTimeBlocksGet']>>>
export type GetAllCampusesCampusesGetResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getAutomatedCourseSchedulerAPI>['getAllCampusesCampusesGet']>>>
export type CreateCampusCampusesPostResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getAutomatedCourseSchedulerAPI>['createCampusCampusesPost']>>>
export type GetCampusCampusesCampusIdGetResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getAutomatedCourseSchedulerAPI>['getCampusCampusesCampusIdGet']>>>
export type UpdateCampusCampusesCampusIdPutResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getAutomatedCourseSchedulerAPI>['updateCampusCampusesCampusIdPut']>>>
export type DeleteCampusCampusesCampusIdDeleteResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getAutomatedCourseSchedulerAPI>['deleteCampusCampusesCampusIdDelete']>>>
export type UploadCoursesUploadCoursesPostResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getAutomatedCourseSchedulerAPI>['uploadCoursesUploadCoursesPost']>>>
export type UploadFacultyPreferencesUploadFacultyPreferencesPostResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getAutomatedCourseSchedulerAPI>['uploadFacultyPreferencesUploadFacultyPreferencesPost']>>>
export type UploadTimePreferencesUploadTimePreferencesPostResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getAutomatedCourseSchedulerAPI>['uploadTimePreferencesUploadTimePreferencesPost']>>>
export type PostCommentCommentsPostResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getAutomatedCourseSchedulerAPI>['postCommentCommentsPost']>>>
export type PostReplyCommentsParentIdPostResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getAutomatedCourseSchedulerAPI>['postReplyCommentsParentIdPost']>>>
export type GetCommentsCommentsSectionIdGetResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getAutomatedCourseSchedulerAPI>['getCommentsCommentsSectionIdGet']>>>
export type DeleteCommentCommentsCommentIdDeleteResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getAutomatedCourseSchedulerAPI>['deleteCommentCommentsCommentIdDelete']>>>
export type ResolveCommentCommentsCommentIdPutResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getAutomatedCourseSchedulerAPI>['resolveCommentCommentsCommentIdPut']>>>
export type AcquireLockSectionsSectionIdLockPostResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getAutomatedCourseSchedulerAPI>['acquireLockSectionsSectionIdLockPost']>>>
export type ReleaseLockSectionsSectionIdUnlockPostResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getAutomatedCourseSchedulerAPI>['releaseLockSectionsSectionIdUnlockPost']>>>
export type CreateInviteApiInvitesPostResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getAutomatedCourseSchedulerAPI>['createInviteApiInvitesPost']>>>
export type ExportInvitesApiInvitesExportGetResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getAutomatedCourseSchedulerAPI>['exportInvitesApiInvitesExportGet']>>>
export type ListUsersApiUsersGetResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getAutomatedCourseSchedulerAPI>['listUsersApiUsersGet']>>>
export type GetMeApiUsersMeGetResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getAutomatedCourseSchedulerAPI>['getMeApiUsersMeGet']>>>
export type GetUserApiUsersUserIdGetResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getAutomatedCourseSchedulerAPI>['getUserApiUsersUserIdGet']>>>
export type RootGetResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getAutomatedCourseSchedulerAPI>['rootGet']>>>
