/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */
import { axiosInstance } from './axiosInstance';
export type SectionResponseSchedule = number | null;

export type SectionResponseTimeBlock = number | null;

export type SectionResponseCourse = number | null;

export type SectionResponseCapacity = number | null;

export type SectionResponseInstructor = number | null;

export interface SectionResponse {
  SectionID: number;
  Schedule: SectionResponseSchedule;
  TimeBlock: SectionResponseTimeBlock;
  Course: SectionResponseCourse;
  Capacity: SectionResponseCapacity;
  Instructor: SectionResponseInstructor;
}

export const getFastAPI = () => {
/**
 * @summary Get Sections
 */
const getSectionsSectionsGet = (
    
 ) => {
      return axiosInstance<SectionResponse[]>(
      {url: `/sections`, method: 'GET'
    },
      );
    }
  
return {getSectionsSectionsGet}};
export type GetSectionsSectionsGetResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getFastAPI>['getSectionsSectionsGet']>>>
