/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Automated Course Scheduler API
 * API for the Automated Course Scheduler system
 * OpenAPI spec version: 1.0.0
 */
import { axiosInstance } from './axiosInstance';
export interface BodyUploadCoursesUploadCoursesPost {
  file: string;
}

export interface BodyUploadFacultyPreferencesUploadFacultyPreferencesPost {
  file: string;
}

export interface CampusResponse {
  CampusID: number;
  CampusName: string;
}

export type CommentScheduleId = number | null;

export type CommentSectionId = number | null;

export interface Comment {
  comment_id: number;
  schedule_id?: CommentScheduleId;
  section_id?: CommentSectionId;
  user_id: number;
  content: string;
  created_at: string;
}

export type CommentCreateScheduleId = number | null;

export type CommentCreateSectionId = number | null;

export interface CommentCreate {
  schedule_id?: CommentCreateScheduleId;
  section_id?: CommentCreateSectionId;
  content: string;
}

export interface CourseInfo {
  course_id: number;
  name: string;
  description: string;
  credits: number;
}

export interface CoursePreferenceInfo {
  course_id: number;
  course_name: string;
  preference: string;
}

export type CourseResponseCourseDescription = string | null;

export type CourseResponseCourseNo = number | null;

export type CourseResponseCourseSubject = string | null;

export type CourseResponseCourseName = string | null;

export type CourseResponseSectionCount = number | null;

export interface CourseResponse {
  CourseID: number;
  CourseDescription?: CourseResponseCourseDescription;
  CourseNo?: CourseResponseCourseNo;
  CourseSubject?: CourseResponseCourseSubject;
  CourseName?: CourseResponseCourseName;
  SectionCount?: CourseResponseSectionCount;
}

export type FacultyResponseFirstName = string | null;

export type FacultyResponseLastName = string | null;

export type FacultyResponseEmail = string | null;

export type FacultyResponseTitle = string | null;

export type FacultyResponseCampus = number | null;

export type FacultyResponseActive = boolean | null;

export type FacultyResponseMaxLoad = number | null;

export interface FacultyResponse {
  NUID: number;
  FirstName?: FacultyResponseFirstName;
  LastName?: FacultyResponseLastName;
  Email?: FacultyResponseEmail;
  Title?: FacultyResponseTitle;
  Campus?: FacultyResponseCampus;
  Active?: FacultyResponseActive;
  MaxLoad?: FacultyResponseMaxLoad;
}

export interface HTTPValidationError {
  detail?: ValidationError[];
}

export interface InstructorInfo {
  nuid: number;
  first_name: string;
  last_name: string;
  title: string;
  email: string;
  course_preferences: CoursePreferenceInfo[];
  meeting_preferences: MeetingPreferenceInfo[];
}

export interface MeetingPreferenceInfo {
  meeting_time: string;
  preference: string;
}

export interface ScheduleCreate {
  ScheduleName: string;
  SemesterSeason: string;
  SemesterYear: number;
  Campus: number;
}

export type ScheduleResponseScheduleName = string | null;

export type ScheduleResponseSemesterSeason = string | null;

export type ScheduleResponseSemesterYear = number | null;

export type ScheduleResponseCampus = number | null;

export type ScheduleResponseComplete = boolean | null;

export interface ScheduleResponse {
  ScheduleID: number;
  ScheduleName?: ScheduleResponseScheduleName;
  SemesterSeason?: ScheduleResponseSemesterSeason;
  SemesterYear?: ScheduleResponseSemesterYear;
  Campus?: ScheduleResponseCampus;
  Complete?: ScheduleResponseComplete;
}

export type ScheduleUpdateScheduleName = string | null;

export type ScheduleUpdateComplete = boolean | null;

export interface ScheduleUpdate {
  ScheduleName?: ScheduleUpdateScheduleName;
  Complete?: ScheduleUpdateComplete;
}

export interface SectionCreate {
  schedule_id: number;
  time_block_id: number;
  course_id: number;
  capacity: number;
  section_number: number;
}

export interface SectionResponse {
  section_id: number;
  schedule_id: number;
  time_block_id: number;
  course_id: number;
  capacity: number;
  section_number: number;
}

export interface SectionRichResponse {
  section_id: number;
  section_number: number;
  capacity: number;
  schedule_id: number;
  course: CourseInfo;
  time_block: TimeBlockInfo;
  instructors: InstructorInfo[];
}

export type SectionUpdateTimeBlockId = number | null;

export type SectionUpdateCourseId = number | null;

export type SectionUpdateCapacity = number | null;

export interface SectionUpdate {
  time_block_id?: SectionUpdateTimeBlockId;
  course_id?: SectionUpdateCourseId;
  capacity?: SectionUpdateCapacity;
}

export interface TimeBlockInfo {
  time_block_id: number;
  days: string;
  start_time: string;
  end_time: string;
  timezone: string;
}

export type TimeBlockResponseBlockID = number | null;

export type TimeBlockResponseCampusID = number | null;

export type TimeBlockResponseCount = number | null;

/**
 * CampusTimeBlock.
 */
export interface TimeBlockResponse {
  BlockID?: TimeBlockResponseBlockID;
  CampusID?: TimeBlockResponseCampusID;
  Count?: TimeBlockResponseCount;
}

export type UploadResponseErrors = string[] | null;

export interface UploadResponse {
  status: string;
  message: string;
  records_processed?: number;
  records_successful?: number;
  records_failed?: number;
  errors?: UploadResponseErrors;
}

export type ValidationErrorLocItem = string | number;

export type ValidationErrorCtx = { [key: string]: unknown };

export interface ValidationError {
  loc: ValidationErrorLocItem[];
  msg: string;
  type: string;
  input?: unknown;
  ctx?: ValidationErrorCtx;
}

export type GetSchedulesSchedulesGetParams = {
/**
 * Filter by campus ID
 */
campus_id?: number | null;
/**
 * Filter by semester season
 */
semester_season?: string | null;
/**
 * Filter by semester year
 */
semester_year?: number | null;
};

export type GetFacultyFacultyGetParams = {
/**
 * Filter by campus ID
 */
campus_id?: number | null;
/**
 * Filter to only active faculty
 */
active_only?: boolean;
};

export type GetTimeBlocksTimeBlocksGetParams = {
/**
 * Filter by campus ID
 */
campus_id?: number | null;
};

export type GetCommentsCommentsGetParams = {
/**
 * Filter by schedule ID
 */
schedule_id?: number | null;
};

export const getAutomatedCourseSchedulerAPI = () => {
/**
 * Get all sections with denormalized course, time block, and instructor data.
 * @summary Get Rich Sections
 */
const getRichSectionsSectionsScheduleIdRichGet = (
    scheduleId: number,
 ) => {
      return axiosInstance<SectionRichResponse[]>(
      {url: `/sections/${scheduleId}/rich`, method: 'GET'
    },
      );
    }
  
/**
 * Get all sections.
 * @summary Get Sections
 */
const getSectionsSectionsScheduleIdGet = (
    scheduleId: number,
 ) => {
      return axiosInstance<SectionResponse[]>(
      {url: `/sections/${scheduleId}`, method: 'GET'
    },
      );
    }
  
/**
 * Create a new section in a schedule.
 * @summary Create Section
 */
const createSectionSectionsPost = (
    sectionCreate: SectionCreate,
 ) => {
      return axiosInstance<SectionResponse>(
      {url: `/sections`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: sectionCreate
    },
      );
    }
  
/**
 * Update an existing section.
 * @summary Update Section
 */
const updateSectionSectionsSectionIdPut = (
    sectionId: number,
    sectionUpdate: SectionUpdate,
 ) => {
      return axiosInstance<SectionResponse>(
      {url: `/sections/${sectionId}`, method: 'PUT',
      headers: {'Content-Type': 'application/json', },
      data: sectionUpdate
    },
      );
    }
  
/**
 * Delete a section from a schedule.
 * @summary Delete Section
 */
const deleteSectionSectionsSectionIdDelete = (
    sectionId: number,
 ) => {
      return axiosInstance<void>(
      {url: `/sections/${sectionId}`, method: 'DELETE'
    },
      );
    }
  
/**
 * Retrieve all schedules, optionally filtered by campus or semester.
 * @summary Get Schedules
 */
const getSchedulesSchedulesGet = (
    params?: GetSchedulesSchedulesGetParams,
 ) => {
      return axiosInstance<ScheduleResponse[]>(
      {url: `/schedules`, method: 'GET',
        params
    },
      );
    }
  
/**
 * Create a new schedule draft.
 * @summary Create Schedule
 */
const createScheduleSchedulesPost = (
    scheduleCreate: ScheduleCreate,
 ) => {
      return axiosInstance<ScheduleResponse>(
      {url: `/schedules`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: scheduleCreate
    },
      );
    }
  
/**
 * Retrieve a specific schedule.
 * @summary Get Schedule
 */
const getScheduleSchedulesScheduleIdGet = (
    scheduleId: number,
 ) => {
      return axiosInstance<ScheduleResponse>(
      {url: `/schedules/${scheduleId}`, method: 'GET'
    },
      );
    }
  
/**
 * Update schedule metadata (name, complete status, etc.).
 * @summary Update Schedule
 */
const updateScheduleSchedulesScheduleIdPut = (
    scheduleId: number,
    scheduleUpdate: ScheduleUpdate,
 ) => {
      return axiosInstance<ScheduleResponse>(
      {url: `/schedules/${scheduleId}`, method: 'PUT',
      headers: {'Content-Type': 'application/json', },
      data: scheduleUpdate
    },
      );
    }
  
/**
 * Delete a schedule and all its sections.
 * @summary Delete Schedule
 */
const deleteScheduleSchedulesScheduleIdDelete = (
    scheduleId: number,
 ) => {
      return axiosInstance<void>(
      {url: `/schedules/${scheduleId}`, method: 'DELETE'
    },
      );
    }
  
/**
 * Get all sections for a specific schedule.
 * @summary Get Schedule Sections
 */
const getScheduleSectionsSchedulesScheduleIdSectionsGet = (
    scheduleId: number,
 ) => {
      return axiosInstance<SectionResponse[]>(
      {url: `/schedules/${scheduleId}/sections`, method: 'GET'
    },
      );
    }
  
/**
 * Trigger the scheduling algorithm to generate a draft schedule.
 * @summary Generate Schedule
 */
const generateScheduleSchedulesScheduleIdGeneratePost = (
    scheduleId: number,
 ) => {
      return axiosInstance<ScheduleResponse>(
      {url: `/schedules/${scheduleId}/generate`, method: 'POST'
    },
      );
    }
  
/**
 * Export a finalized schedule in CourseLeaf-compatible CSV format.
 * @summary Export Schedule Csv
 */
const exportScheduleCsvSchedulesScheduleIdExportCsvGet = (
    scheduleId: number,
 ) => {
      return axiosInstance<unknown>(
      {url: `/schedules/${scheduleId}/export/csv`, method: 'GET'
    },
      );
    }
  
/**
 * Retrieve all courses.
 * @summary Get Courses
 */
const getCoursesCoursesGet = (
    
 ) => {
      return axiosInstance<CourseResponse[]>(
      {url: `/courses`, method: 'GET'
    },
      );
    }
  
/**
 * Retrieve all faculty members.
 * @summary Get Faculty
 */
const getFacultyFacultyGet = (
    params?: GetFacultyFacultyGetParams,
 ) => {
      return axiosInstance<FacultyResponse[]>(
      {url: `/faculty`, method: 'GET',
        params
    },
      );
    }
  
/**
 * Retrieve all time blocks, optionally filtered by campus.
 * @summary Get Time Blocks
 */
const getTimeBlocksTimeBlocksGet = (
    params?: GetTimeBlocksTimeBlocksGetParams,
 ) => {
      return axiosInstance<TimeBlockResponse[]>(
      {url: `/time-blocks`, method: 'GET',
        params
    },
      );
    }
  
/**
 * Retrieve all campuses.
 * @summary Get Campuses
 */
const getCampusesCampusesGet = (
    
 ) => {
      return axiosInstance<CampusResponse[]>(
      {url: `/campuses`, method: 'GET'
    },
      );
    }
  
/**
 * Upload a CSV file containing course offering data.
 * @summary Upload Courses
 */
const uploadCoursesUploadCoursesPost = (
    bodyUploadCoursesUploadCoursesPost: BodyUploadCoursesUploadCoursesPost,
 ) => {const formData = new FormData();
formData.append(`file`, bodyUploadCoursesUploadCoursesPost.file)

      return axiosInstance<UploadResponse>(
      {url: `/upload/courses`, method: 'POST',
      headers: {'Content-Type': 'multipart/form-data', },
       data: formData
    },
      );
    }
  
/**
 * Upload a CSV file containing faculty preference data.
 * @summary Upload Faculty Preferences
 */
const uploadFacultyPreferencesUploadFacultyPreferencesPost = (
    bodyUploadFacultyPreferencesUploadFacultyPreferencesPost: BodyUploadFacultyPreferencesUploadFacultyPreferencesPost,
 ) => {const formData = new FormData();
formData.append(`file`, bodyUploadFacultyPreferencesUploadFacultyPreferencesPost.file)

      return axiosInstance<UploadResponse>(
      {url: `/upload/faculty-preferences`, method: 'POST',
      headers: {'Content-Type': 'multipart/form-data', },
       data: formData
    },
      );
    }
  
/**
 * Get comments, optionally filtered by schedule.
 * @summary Get Comments
 */
const getCommentsCommentsGet = (
    params?: GetCommentsCommentsGetParams,
 ) => {
      return axiosInstance<Comment[]>(
      {url: `/comments`, method: 'GET',
        params
    },
      );
    }
  
/**
 * Create a new comment on a schedule component.
 * @summary Create Comment
 */
const createCommentCommentsPost = (
    commentCreate: CommentCreate,
 ) => {
      return axiosInstance<Comment>(
      {url: `/comments`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: commentCreate
    },
      );
    }
  
/**
 * @summary Root
 */
const rootGet = (
    
 ) => {
      return axiosInstance<unknown>(
      {url: `/`, method: 'GET'
    },
      );
    }
  
return {getRichSectionsSectionsScheduleIdRichGet,getSectionsSectionsScheduleIdGet,createSectionSectionsPost,updateSectionSectionsSectionIdPut,deleteSectionSectionsSectionIdDelete,getSchedulesSchedulesGet,createScheduleSchedulesPost,getScheduleSchedulesScheduleIdGet,updateScheduleSchedulesScheduleIdPut,deleteScheduleSchedulesScheduleIdDelete,getScheduleSectionsSchedulesScheduleIdSectionsGet,generateScheduleSchedulesScheduleIdGeneratePost,exportScheduleCsvSchedulesScheduleIdExportCsvGet,getCoursesCoursesGet,getFacultyFacultyGet,getTimeBlocksTimeBlocksGet,getCampusesCampusesGet,uploadCoursesUploadCoursesPost,uploadFacultyPreferencesUploadFacultyPreferencesPost,getCommentsCommentsGet,createCommentCommentsPost,rootGet}};
export type GetRichSectionsSectionsScheduleIdRichGetResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getAutomatedCourseSchedulerAPI>['getRichSectionsSectionsScheduleIdRichGet']>>>
export type GetSectionsSectionsScheduleIdGetResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getAutomatedCourseSchedulerAPI>['getSectionsSectionsScheduleIdGet']>>>
export type CreateSectionSectionsPostResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getAutomatedCourseSchedulerAPI>['createSectionSectionsPost']>>>
export type UpdateSectionSectionsSectionIdPutResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getAutomatedCourseSchedulerAPI>['updateSectionSectionsSectionIdPut']>>>
export type DeleteSectionSectionsSectionIdDeleteResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getAutomatedCourseSchedulerAPI>['deleteSectionSectionsSectionIdDelete']>>>
export type GetSchedulesSchedulesGetResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getAutomatedCourseSchedulerAPI>['getSchedulesSchedulesGet']>>>
export type CreateScheduleSchedulesPostResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getAutomatedCourseSchedulerAPI>['createScheduleSchedulesPost']>>>
export type GetScheduleSchedulesScheduleIdGetResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getAutomatedCourseSchedulerAPI>['getScheduleSchedulesScheduleIdGet']>>>
export type UpdateScheduleSchedulesScheduleIdPutResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getAutomatedCourseSchedulerAPI>['updateScheduleSchedulesScheduleIdPut']>>>
export type DeleteScheduleSchedulesScheduleIdDeleteResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getAutomatedCourseSchedulerAPI>['deleteScheduleSchedulesScheduleIdDelete']>>>
export type GetScheduleSectionsSchedulesScheduleIdSectionsGetResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getAutomatedCourseSchedulerAPI>['getScheduleSectionsSchedulesScheduleIdSectionsGet']>>>
export type GenerateScheduleSchedulesScheduleIdGeneratePostResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getAutomatedCourseSchedulerAPI>['generateScheduleSchedulesScheduleIdGeneratePost']>>>
export type ExportScheduleCsvSchedulesScheduleIdExportCsvGetResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getAutomatedCourseSchedulerAPI>['exportScheduleCsvSchedulesScheduleIdExportCsvGet']>>>
export type GetCoursesCoursesGetResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getAutomatedCourseSchedulerAPI>['getCoursesCoursesGet']>>>
export type GetFacultyFacultyGetResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getAutomatedCourseSchedulerAPI>['getFacultyFacultyGet']>>>
export type GetTimeBlocksTimeBlocksGetResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getAutomatedCourseSchedulerAPI>['getTimeBlocksTimeBlocksGet']>>>
export type GetCampusesCampusesGetResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getAutomatedCourseSchedulerAPI>['getCampusesCampusesGet']>>>
export type UploadCoursesUploadCoursesPostResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getAutomatedCourseSchedulerAPI>['uploadCoursesUploadCoursesPost']>>>
export type UploadFacultyPreferencesUploadFacultyPreferencesPostResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getAutomatedCourseSchedulerAPI>['uploadFacultyPreferencesUploadFacultyPreferencesPost']>>>
export type GetCommentsCommentsGetResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getAutomatedCourseSchedulerAPI>['getCommentsCommentsGet']>>>
export type CreateCommentCommentsPostResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getAutomatedCourseSchedulerAPI>['createCommentCommentsPost']>>>
export type RootGetResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getAutomatedCourseSchedulerAPI>['rootGet']>>>
